# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#id2
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: mambaforge-latest
  # https://jupyterbook.org/en/stable/publish/readthedocs.html
  jobs:
    pre_build:
      - jupyter-book config sphinx .

# The `make` command uses this to build the docs
html:
  theme: sphinx_rtd_theme  # or another theme if you're using a custom one

conda:
  environment: environment.yaml